### ISSUE TITLE
Strange Error

### ISSUE THREAD

**Issue by LordRazor** [cryptic-game/server#8]
Well, it just appears multiple times in the Console.

```
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
         at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
         at java.lang.Runtime.loadLibrary0(Runtime.java:870)
         at java.lang.System.loadLibrary(System.java:1122)
         at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
         at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:349)
         at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
         at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:198)
         at io.netty.channel.epoll.Native.<clinit>(Native.java:61)
         at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:38)
         at net.cryptic_game.server.socket.SocketSever.<clinit>(SocketSever.java:21)
         at net.cryptic_game.server.App.main(App.java:26)
         Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
                 at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
                 at java.lang.Runtime.loadLibrary0(Runtime.java:870)
                 at java.lang.System.loadLibrary(System.java:1122)
                 at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                 at java.lang.reflect.Method.invoke(Method.java:498)
                 at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)               at java.security.AccessController.doPrivileged(Native Method)
                at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
                 at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
```

**Comment by use-to** [comment]
Thank you for submitting this issue. 
Fixed in 0.0.8
